name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

  workflow_dispatch:

  schedule:
  - cron: '0 9 * * 1'

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install Python dependencies
      run: cd build/ && pip install -r requirements.txt

    - name: Run build script
      run: cd build/ && ./main.sh

    - name: Login to Tencent Cloud Container Registry
      run: echo "${{ secrets.TENCENT_REGISTRY_PASSWORD }}" | docker login ccr.ccs.tencentyun.com --username ${{ secrets.TENCENT_REGISTRY_USERNAME }} --password-stdin

    - name: Build Docker image
      run: cd server/ && docker build -t yindian-server .

    - name: Tag Docker image
      run: docker tag yindian-server:latest ccr.ccs.tencentyun.com/nk2028/yindian-server:latest

    - name: Push to registry
      run: docker push ccr.ccs.tencentyun.com/nk2028/yindian-server:latest

    - name: Install Tencent Cloud CLI tools
      run: pip install -r requirements.txt

    - name: Deploy to Tencent Cloud
      run: tccli scf UpdateFunctionCode --cli-unfold-argument --region ap-guangzhou --FunctionName yindian-server --Code.ImageConfig.ImageType personal --Code.ImageConfig.ImageUri 'ccr.ccs.tencentyun.com/nk2028/yindian-server:latest' --Code.ImageConfig.ContainerImageAccelerate True
      env:
        TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENTCLOUD_SCF_SECRET_ID }}
        TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SCF_SECRET_KEY }}
